FROM alpine as chromium_stage
RUN sed -i "s/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g" /etc/apk/repositories \
      && apk add --no-cache wget \
      && apk add --update chromium

FROM alpine 
COPY --from=chromium_stage /usr/lib/chromium/chrome  /chrome
COPY ./crawlergo /crawlergo
COPY ./dirsearch.txt /dirsearch.txt
ENTRYPOINT ["/crawlergo","-c","/chrome","-f","strict","--fuzz-path","--robots-path"," --fuzz-path-dict","/dirsearch.txt"]
